/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's repository.
*/

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GrovePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian3 = require("obsidian");

// src/runner.ts
var import_child_process = require("child_process");
var import_obsidian = require("obsidian");
var GroveRunner = class {
  constructor(cliPath, cwd, apiKey) {
    this.activeProcess = null;
    this.cliPath = cliPath;
    this.cwd = cwd;
    this.apiKey = apiKey;
  }
  /** Update runner configuration without creating a new instance. */
  setCwd(cwd) {
    this.cwd = cwd;
  }
  setCliPath(cliPath) {
    this.cliPath = cliPath;
  }
  setApiKey(apiKey) {
    this.apiKey = apiKey;
  }
  /** Returns true if a subprocess is currently running. */
  isRunning() {
    return this.activeProcess !== null;
  }
  /**
   * Run a grove CLI command with `--json` flag and stream NDJSON events.
   *
   * @param args  CLI arguments, e.g. ["compile"] or ["query", "--deep", "What is..."]
   * @param onEvent  Callback invoked for each parsed NDJSON event
   * @returns A promise that resolves when the process exits normally,
   *          or rejects on a non-zero exit code / crash.
   */
  run(args, onEvent) {
    return new Promise((resolve, reject) => {
      var _a, _b;
      if (this.activeProcess) {
        reject(new Error("A grove process is already running. Please wait for it to finish."));
        return;
      }
      const fullArgs = [...args, "--json"];
      const env = { ...process.env };
      if (this.apiKey) {
        env["ANTHROPIC_API_KEY"] = this.apiKey;
      }
      let child;
      try {
        child = (0, import_child_process.spawn)(this.cliPath, fullArgs, {
          cwd: this.cwd,
          env,
          stdio: ["ignore", "pipe", "pipe"]
        });
      } catch (err) {
        reject(new Error(`Failed to start grove CLI at "${this.cliPath}": ${String(err)}`));
        return;
      }
      this.activeProcess = child;
      let stdoutBuffer = "";
      let stderrChunks = "";
      (_a = child.stdout) == null ? void 0 : _a.on("data", (chunk) => {
        var _a2;
        stdoutBuffer += chunk.toString("utf-8");
        const lines = stdoutBuffer.split("\n");
        stdoutBuffer = (_a2 = lines.pop()) != null ? _a2 : "";
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed) continue;
          try {
            const event = JSON.parse(trimmed);
            onEvent(event);
          } catch (e) {
          }
        }
      });
      (_b = child.stderr) == null ? void 0 : _b.on("data", (chunk) => {
        stderrChunks += chunk.toString("utf-8");
      });
      child.on("error", (err) => {
        this.activeProcess = null;
        reject(new Error(`Grove CLI process error: ${err.message}`));
      });
      child.on("close", (code, signal) => {
        this.activeProcess = null;
        if (stdoutBuffer.trim()) {
          try {
            const event = JSON.parse(stdoutBuffer.trim());
            onEvent(event);
          } catch (e) {
          }
        }
        if (signal) {
          reject(new Error(`Grove CLI was killed by signal ${signal}`));
        } else if (code !== null && code !== 0) {
          const stderrMsg = stderrChunks.trim();
          reject(
            new Error(
              `Grove CLI exited with code ${code}${stderrMsg ? `: ${stderrMsg}` : ""}`
            )
          );
        } else {
          resolve();
        }
      });
    });
  }
  /** Kill the active subprocess, if any. */
  kill() {
    if (this.activeProcess) {
      this.activeProcess.kill("SIGTERM");
      this.activeProcess = null;
    }
  }
};
async function detectGroveCli() {
  const { execFile } = await import("child_process");
  const { promisify } = await import("util");
  const execFileAsync = promisify(execFile);
  const candidates = [
    "/usr/local/bin/grove",
    "/opt/homebrew/bin/grove",
    `${process.env["HOME"]}/.local/bin/grove`
  ];
  const { existsSync: existsSync2 } = await import("fs");
  for (const candidate of candidates) {
    if (existsSync2(candidate)) {
      return candidate;
    }
  }
  try {
    const { stdout } = await execFileAsync("which", ["grove"]);
    const path2 = stdout.trim();
    if (path2) return path2;
  } catch (e) {
  }
  return null;
}
function notifyRunnerError(err) {
  const msg = err instanceof Error ? err.message : String(err);
  if (msg.includes("ENOENT") || msg.includes("Failed to start")) {
    new import_obsidian.Notice("Grove CLI not found. Check the CLI path in Grove settings.", 8e3);
  } else if (msg.includes("already running")) {
    new import_obsidian.Notice("A Grove process is already running. Please wait.", 5e3);
  } else {
    new import_obsidian.Notice(`Grove error: ${msg}`, 8e3);
  }
}

// src/grove-detector.ts
var import_obsidian2 = require("obsidian");
var path = __toESM(require("path"));
var fs = __toESM(require("fs"));
var GroveDetector = class {
  constructor(app) {
    this.detectedGroves = [];
    this.app = app;
  }
  /**
   * Scan the vault filesystem for directories containing `.grove/config.yaml`.
   * Searches up to 3 levels deep to avoid excessive traversal on large vaults.
   */
  async scan() {
    this.detectedGroves = [];
    const vaultRoot = this.getVaultBasePath();
    if (!vaultRoot) return [];
    await this.scanDirectory(vaultRoot, vaultRoot, 0, 3);
    return this.detectedGroves;
  }
  /** Returns the last scan results without re-scanning. */
  getDetectedGroves() {
    return this.detectedGroves;
  }
  /** Returns the vault's absolute filesystem path. */
  getVaultBasePath() {
    const adapter = this.app.vault.adapter;
    if ("getBasePath" in adapter && typeof adapter.getBasePath === "function") {
      return adapter.getBasePath();
    }
    return null;
  }
  /**
   * Recursively scan directories looking for .grove/config.yaml.
   * Skips hidden directories (except .grove itself), node_modules, and similar.
   */
  async scanDirectory(dir, vaultRoot, depth, maxDepth) {
    if (depth > maxDepth) return;
    const groveConfigPath = path.join(dir, ".grove", "config.yaml");
    try {
      if (fs.existsSync(groveConfigPath)) {
        const relativePath = path.relative(vaultRoot, dir);
        this.detectedGroves.push({
          rootPath: dir,
          label: relativePath || "(vault root)"
        });
      }
    } catch (e) {
      return;
    }
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch (e) {
      return;
    }
    const skipDirs = /* @__PURE__ */ new Set([
      ".git",
      ".obsidian",
      ".grove",
      "node_modules",
      "__pycache__",
      ".venv",
      "venv"
    ]);
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      if (entry.name.startsWith(".") && !skipDirs.has(entry.name)) continue;
      if (skipDirs.has(entry.name)) continue;
      await this.scanDirectory(
        path.join(dir, entry.name),
        vaultRoot,
        depth + 1,
        maxDepth
      );
    }
  }
};
function addGroveSelector(containerEl, plugin, detectedGroves) {
  if (detectedGroves.length === 0) {
    new import_obsidian2.Setting(containerEl).setName("Detected groves").setDesc(
      "No grove directories found in this vault. Run 'grove init' in a directory to create one, or set the path manually below."
    );
    return;
  }
  if (detectedGroves.length === 1) {
    const grove = detectedGroves[0];
    new import_obsidian2.Setting(containerEl).setName("Detected grove").setDesc(`Found: ${grove.label}`);
    if (!plugin.settings.defaultGrovePath) {
      plugin.settings.defaultGrovePath = grove.rootPath;
      plugin.saveSettings();
    }
    return;
  }
  new import_obsidian2.Setting(containerEl).setName("Active grove").setDesc(
    `${detectedGroves.length} grove directories found in this vault. Select which one to use for compile and query commands.`
  ).addDropdown((dropdown) => {
    for (const grove of detectedGroves) {
      dropdown.addOption(grove.rootPath, grove.label);
    }
    const current = plugin.settings.defaultGrovePath;
    if (current && detectedGroves.some((g) => g.rootPath === current)) {
      dropdown.setValue(current);
    } else {
      dropdown.setValue(detectedGroves[0].rootPath);
      plugin.settings.defaultGrovePath = detectedGroves[0].rootPath;
      plugin.saveSettings();
    }
    dropdown.onChange(async (value) => {
      plugin.settings.defaultGrovePath = value;
      await plugin.saveSettings();
      new import_obsidian2.Notice(`Active grove set to: ${value}`);
    });
  });
}
function resolveGroveCwd(plugin) {
  const configured = plugin.settings.defaultGrovePath;
  if (configured && fs.existsSync(configured)) {
    return configured;
  }
  const adapter = plugin.app.vault.adapter;
  if ("getBasePath" in adapter && typeof adapter.getBasePath === "function") {
    return adapter.getBasePath();
  }
  return process.cwd();
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  anthropicApiKey: "",
  groveCliPath: "/usr/local/bin/grove",
  defaultGrovePath: "",
  dryRunByDefault: false,
  defaultQueryMode: "deep"
};
var GroveSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Grove \u2014 Settings" });
    new import_obsidian3.Setting(containerEl).setName("Anthropic API key").setDesc(
      "Your API key is stored locally in this vault's plugin data. It is passed to the grove CLI via an environment variable and never written to any grove-tracked file."
    ).addText((text) => {
      text.inputEl.type = "password";
      text.inputEl.autocomplete = "off";
      text.setPlaceholder("sk-ant-...").setValue(this.plugin.settings.anthropicApiKey).onChange(async (value) => {
        this.plugin.settings.anthropicApiKey = value;
        await this.plugin.saveSettings();
      });
    });
    const cliPathSetting = new import_obsidian3.Setting(containerEl).setName("Grove CLI path").setDesc(
      "Absolute path to the grove binary. Use the auto-detect button to search common installation locations."
    ).addText((text) => {
      text.setPlaceholder("/usr/local/bin/grove").setValue(this.plugin.settings.groveCliPath).onChange(async (value) => {
        this.plugin.settings.groveCliPath = value;
        await this.plugin.saveSettings();
      });
    });
    cliPathSetting.addButton((button) => {
      button.setButtonText("Auto-detect").onClick(async () => {
        button.setDisabled(true);
        button.setButtonText("Searching...");
        const detected = await detectGroveCli();
        if (detected) {
          this.plugin.settings.groveCliPath = detected;
          await this.plugin.saveSettings();
          new import_obsidian3.Notice(`Grove CLI found: ${detected}`);
          this.display();
        } else {
          new import_obsidian3.Notice(
            "Could not find the grove CLI. Install it with: pip install grove-kb",
            8e3
          );
        }
        button.setDisabled(false);
        button.setButtonText("Auto-detect");
      });
    });
    containerEl.createEl("h3", { text: "Grove detection" });
    const detectorSection = containerEl.createDiv({ cls: "grove-detector-section" });
    detectorSection.createEl("p", {
      text: "Scanning vault for grove directories...",
      cls: "grove-detector-status"
    });
    const detector = new GroveDetector(this.app);
    detector.scan().then((groves) => {
      detectorSection.empty();
      addGroveSelector(detectorSection, this.plugin, groves);
      if (groves.length === 1 && !this.plugin.settings.defaultGrovePath) {
        this.plugin.settings.defaultGrovePath = groves[0].rootPath;
        this.plugin.saveSettings();
      }
    });
    new import_obsidian3.Setting(containerEl).addButton((button) => {
      button.setButtonText("Rescan vault").onClick(async () => {
        button.setDisabled(true);
        button.setButtonText("Scanning...");
        const groves = await detector.scan();
        detectorSection.empty();
        addGroveSelector(detectorSection, this.plugin, groves);
        button.setDisabled(false);
        button.setButtonText("Rescan vault");
        new import_obsidian3.Notice(`Found ${groves.length} grove ${groves.length === 1 ? "directory" : "directories"}.`);
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Active grove path (manual override)").setDesc(
      "The working directory for grove commands. Leave blank to use auto-detected grove, or enter a path outside the vault."
    ).addText((text) => {
      text.setPlaceholder("(auto-detected)").setValue(this.plugin.settings.defaultGrovePath).onChange(async (value) => {
        this.plugin.settings.defaultGrovePath = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Dry-run by default").setDesc(
      "When enabled, the Compile command shows estimated tokens and cost without making LLM calls or modifying files."
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.dryRunByDefault).onChange(async (value) => {
        this.plugin.settings.dryRunByDefault = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Default query mode").setDesc(
      "Quick: searches the index only, faster but less thorough. Deep: loads relevant articles and synthesises a full answer."
    ).addDropdown((dropdown) => {
      dropdown.addOption("quick", "Quick").addOption("deep", "Deep").setValue(this.plugin.settings.defaultQueryMode).onChange(async (value) => {
        this.plugin.settings.defaultQueryMode = value;
        await this.plugin.saveSettings();
      });
    });
  }
};

// src/compile.ts
var import_obsidian4 = require("obsidian");
var DryRunModal = class extends import_obsidian4.Modal {
  constructor(app, result) {
    super(app);
    this.result = result;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Grove \u2014 Dry-run Estimate" });
    const table = contentEl.createEl("table", { cls: "grove-dry-run-table" });
    const rows = [
      ["Sources", String(this.result.source_count)],
      ["Estimated tokens", this.result.estimated_tokens.toLocaleString()],
      [
        "Estimated cost",
        `$${this.result.estimated_cost_usd.toFixed(2)} USD`
      ]
    ];
    for (const [label, value] of rows) {
      const tr = table.createEl("tr");
      tr.createEl("td", { text: label, cls: "grove-label" });
      tr.createEl("td", { text: value, cls: "grove-value" });
    }
    contentEl.createEl("p", {
      text: "Disable dry-run in Grove settings to perform a real compilation.",
      cls: "grove-dry-run-hint"
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ERROR_REMEDIES = {
  rate_limit: "The Anthropic API rate limit was reached. Wait a few minutes and try again.",
  no_sources: "No sources found. Run 'grove ingest' first to add source material.",
  ratchet_failed: "Quality checks failed. Run 'grove health' to see which checks need attention.",
  budget_exceeded: "Daily budget limit exceeded. Adjust the limit in .grove/config.yaml.",
  no_api_key: "No API key configured. Add your Anthropic API key in Grove settings.",
  config_error: "Configuration error. Check .grove/config.yaml is valid."
};
function getRemedy(code) {
  var _a;
  return (_a = ERROR_REMEDIES[code]) != null ? _a : "Check the grove CLI output for details.";
}
function registerCompileCommand(plugin) {
  plugin.addCommand({
    id: "compile",
    name: "Compile",
    callback: () => {
      runCompile(plugin);
    }
  });
}
async function runCompile(plugin) {
  const runner = plugin.getRunner();
  if (!runner) {
    new import_obsidian4.Notice("Grove runner is not initialised. Check Grove settings.", 5e3);
    return;
  }
  if (runner.isRunning()) {
    new import_obsidian4.Notice("A Grove process is already running. Please wait.", 5e3);
    return;
  }
  const isDryRun = plugin.settings.dryRunByDefault;
  const args = isDryRun ? ["compile", "--dry-run"] : ["compile"];
  const progressNotice = new import_obsidian4.Notice("Grove: Starting compilation...", 0);
  let lastResult = null;
  const onEvent = (event) => {
    var _a;
    switch (event.type) {
      case "progress": {
        const detail = (_a = event.detail) != null ? _a : event.step;
        const pctText = event.pct > 0 ? ` (${event.pct}%)` : "";
        setNoticeMessage(progressNotice, `Grove: ${detail}${pctText}`);
        break;
      }
      case "result":
        lastResult = event;
        break;
      case "warning":
        new import_obsidian4.Notice(`Grove warning: ${event.message}`, 6e3);
        break;
      case "error":
        lastResult = event;
        break;
    }
  };
  try {
    await runner.run(args, onEvent);
    progressNotice.hide();
    if ((lastResult == null ? void 0 : lastResult.type) === "result") {
      const data = lastResult.data;
      if (isDryRun && isDryRunResult(data)) {
        new DryRunModal(plugin.app, data).open();
      } else if (isCompileResult(data)) {
        new import_obsidian4.Notice(
          `Grove: Compilation complete \u2014 ${data.articles_created} created, ${data.articles_updated} updated \u2014 cost: $${data.cost_usd.toFixed(2)}`,
          8e3
        );
      } else {
        new import_obsidian4.Notice("Grove: Compilation complete.", 5e3);
      }
    } else if ((lastResult == null ? void 0 : lastResult.type) === "error") {
      const errEvent = lastResult;
      new import_obsidian4.Notice(
        `Grove error [${errEvent.code}]: ${errEvent.message}
${getRemedy(errEvent.code)}`,
        1e4
      );
    } else {
      new import_obsidian4.Notice("Grove: Compilation finished (no result data received).", 5e3);
    }
  } catch (err) {
    progressNotice.hide();
    notifyRunnerError(err);
  }
}
function setNoticeMessage(notice, message) {
  const el = notice.noticeEl;
  if (el) {
    el.textContent = message;
  }
}
function isCompileResult(data) {
  return typeof data === "object" && data !== null && "articles_created" in data && "articles_updated" in data;
}
function isDryRunResult(data) {
  return typeof data === "object" && data !== null && "estimated_tokens" in data && "estimated_cost_usd" in data;
}

// src/query.ts
var import_obsidian5 = require("obsidian");
var QUERY_VIEW_TYPE = "grove-query-panel";
var GROVE_RIBBON_ICON = "search";
var sessionState = {
  lastQuestion: "",
  lastMode: "deep",
  lastAnswer: "",
  lastCitations: [],
  lastFollowUps: []
};
var QueryPanel = class extends import_obsidian5.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.inputEl = null;
    this.modeSelectEl = null;
    this.submitBtn = null;
    this.fileBtn = null;
    this.answerContainerEl = null;
    this.spinnerEl = null;
    this.isQuerying = false;
    this.plugin = plugin;
  }
  getViewType() {
    return QUERY_VIEW_TYPE;
  }
  getDisplayText() {
    return "Grove Query";
  }
  getIcon() {
    return GROVE_RIBBON_ICON;
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("grove-query-panel");
    container.createEl("h3", { text: "Grove Query" });
    this.inputEl = container.createEl("textarea", {
      cls: "grove-query-input",
      attr: {
        placeholder: "Ask your knowledge base a question...",
        rows: "3"
      }
    });
    this.inputEl.value = sessionState.lastQuestion;
    const controls = container.createDiv({ cls: "grove-query-controls" });
    const modeWrapper = controls.createDiv({ cls: "grove-mode-wrapper" });
    modeWrapper.createEl("label", {
      text: "Mode:",
      attr: { for: "grove-query-mode" }
    });
    this.modeSelectEl = modeWrapper.createEl("select", {
      cls: "grove-mode-select dropdown",
      attr: { id: "grove-query-mode" }
    });
    const quickOption = this.modeSelectEl.createEl("option", {
      text: "Quick",
      attr: { value: "quick" }
    });
    const deepOption = this.modeSelectEl.createEl("option", {
      text: "Deep",
      attr: { value: "deep" }
    });
    const initialMode = sessionState.lastMode || this.plugin.settings.defaultQueryMode;
    if (initialMode === "quick") {
      quickOption.selected = true;
    } else {
      deepOption.selected = true;
    }
    this.submitBtn = controls.createEl("button", {
      text: "Ask",
      cls: "grove-submit-btn mod-cta"
    });
    this.submitBtn.addEventListener("click", () => this.handleSubmit());
    this.spinnerEl = container.createDiv({ cls: "grove-spinner" });
    this.spinnerEl.style.display = "none";
    const spinnerIcon = this.spinnerEl.createDiv({ cls: "grove-spinner-icon" });
    (0, import_obsidian5.setIcon)(spinnerIcon, "loader");
    this.spinnerEl.createSpan({ text: "Querying..." });
    this.answerContainerEl = container.createDiv({ cls: "grove-answer-container" });
    this.fileBtn = container.createEl("button", {
      text: "File this answer",
      cls: "grove-file-btn"
    });
    this.fileBtn.style.display = "none";
    this.fileBtn.addEventListener("click", () => this.handleFile());
    if (sessionState.lastAnswer) {
      await this.renderAnswer(sessionState.lastAnswer);
      this.fileBtn.style.display = "block";
    }
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
        e.preventDefault();
        this.handleSubmit();
      }
    });
  }
  async onClose() {
  }
  // ── Submit handler ────────────────────────────────────────────────
  async handleSubmit() {
    var _a, _b;
    if (this.isQuerying) return;
    if (!this.inputEl || !this.modeSelectEl) return;
    const question = this.inputEl.value.trim();
    if (!question) {
      new import_obsidian5.Notice("Please enter a question.", 3e3);
      return;
    }
    const runner = this.plugin.getRunner();
    if (!runner) {
      new import_obsidian5.Notice("Grove runner is not initialised. Check Grove settings.", 5e3);
      return;
    }
    if (runner.isRunning()) {
      new import_obsidian5.Notice("A Grove process is already running. Please wait.", 5e3);
      return;
    }
    const mode = this.modeSelectEl.value;
    sessionState.lastQuestion = question;
    sessionState.lastMode = mode;
    this.setQuerying(true);
    this.clearAnswer();
    const modeFlag = mode === "quick" ? "--quick" : "--deep";
    const args = ["query", modeFlag, question];
    let queryResult = null;
    try {
      await runner.run(args, (event) => {
        if (event.type === "result" && isQueryResult(event.data)) {
          queryResult = event.data;
        } else if (event.type === "error") {
          new import_obsidian5.Notice(`Grove error: ${event.message}`, 8e3);
        } else if (event.type === "warning") {
          new import_obsidian5.Notice(`Grove warning: ${event.message}`, 6e3);
        }
      });
      if (queryResult) {
        sessionState.lastAnswer = queryResult.answer;
        sessionState.lastCitations = (_a = queryResult.citations) != null ? _a : [];
        sessionState.lastFollowUps = (_b = queryResult.follow_ups) != null ? _b : [];
        await this.renderAnswer(queryResult.answer);
        if (this.fileBtn) {
          this.fileBtn.style.display = "block";
        }
      } else {
        new import_obsidian5.Notice("Grove: No answer received.", 5e3);
      }
    } catch (err) {
      notifyRunnerError(err);
    } finally {
      this.setQuerying(false);
    }
  }
  // ── File handler ──────────────────────────────────────────────────
  async handleFile() {
    if (!sessionState.lastAnswer) {
      new import_obsidian5.Notice("No answer to file.", 3e3);
      return;
    }
    const runner = this.plugin.getRunner();
    if (!runner) {
      new import_obsidian5.Notice("Grove runner is not initialised. Check Grove settings.", 5e3);
      return;
    }
    if (runner.isRunning()) {
      new import_obsidian5.Notice("A Grove process is already running. Please wait.", 5e3);
      return;
    }
    try {
      let filed = false;
      await runner.run(["file"], (event) => {
        if (event.type === "result") {
          filed = true;
        } else if (event.type === "error") {
          new import_obsidian5.Notice(`Grove error: ${event.message}`, 8e3);
        }
      });
      if (filed) {
        new import_obsidian5.Notice("Answer filed to wiki successfully.", 5e3);
      }
    } catch (err) {
      notifyRunnerError(err);
    }
  }
  // ── Rendering helpers ─────────────────────────────────────────────
  async renderAnswer(markdown) {
    if (!this.answerContainerEl) return;
    this.answerContainerEl.empty();
    await import_obsidian5.MarkdownRenderer.renderMarkdown(
      markdown,
      this.answerContainerEl,
      "",
      this
    );
  }
  clearAnswer() {
    if (this.answerContainerEl) {
      this.answerContainerEl.empty();
    }
    if (this.fileBtn) {
      this.fileBtn.style.display = "none";
    }
  }
  setQuerying(active) {
    this.isQuerying = active;
    if (this.spinnerEl) {
      this.spinnerEl.style.display = active ? "flex" : "none";
    }
    if (this.submitBtn) {
      this.submitBtn.disabled = active;
      this.submitBtn.textContent = active ? "Querying..." : "Ask";
    }
    if (this.inputEl) {
      this.inputEl.disabled = active;
    }
    if (this.modeSelectEl) {
      this.modeSelectEl.disabled = active;
    }
  }
};
function registerQueryPanel(plugin) {
  plugin.registerView(
    QUERY_VIEW_TYPE,
    (leaf) => new QueryPanel(leaf, plugin)
  );
  plugin.addRibbonIcon(GROVE_RIBBON_ICON, "Open Grove Query", () => {
    activateQueryPanel(plugin);
  });
  plugin.addCommand({
    id: "open-query",
    name: "Open query panel",
    callback: () => {
      activateQueryPanel(plugin);
    }
  });
}
async function activateQueryPanel(plugin) {
  const { workspace } = plugin.app;
  let leaf = workspace.getLeavesOfType(QUERY_VIEW_TYPE)[0];
  if (!leaf) {
    const rightLeaf = workspace.getRightLeaf(false);
    if (rightLeaf) {
      leaf = rightLeaf;
      await leaf.setViewState({
        type: QUERY_VIEW_TYPE,
        active: true
      });
    }
  }
  if (leaf) {
    workspace.revealLeaf(leaf);
  }
}
function isQueryResult(data) {
  return typeof data === "object" && data !== null && "answer" in data;
}

// src/main.ts
var GrovePlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.runner = null;
  }
  async onload() {
    await this.loadSettings();
    this.initRunner();
    this.addSettingTab(new GroveSettingTab(this.app, this));
    registerCompileCommand(this);
    registerQueryPanel(this);
    console.log("Grove plugin loaded");
  }
  async onunload() {
    if (this.runner) {
      this.runner.kill();
    }
    this.app.workspace.detachLeavesOfType(QUERY_VIEW_TYPE);
    console.log("Grove plugin unloaded");
  }
  // ── Settings persistence ──────────────────────────────────────────
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.initRunner();
  }
  // ── Runner lifecycle ──────────────────────────────────────────────
  /**
   * (Re)initialise the GroveRunner with current settings.
   * Called on load and whenever settings are saved.
   */
  initRunner() {
    const cwd = resolveGroveCwd(this);
    const cliPath = this.settings.groveCliPath;
    const apiKey = this.settings.anthropicApiKey;
    if (this.runner) {
      this.runner.setCliPath(cliPath);
      this.runner.setCwd(cwd);
      this.runner.setApiKey(apiKey);
    } else {
      this.runner = new GroveRunner(cliPath, cwd, apiKey);
    }
  }
  /**
   * Returns the shared GroveRunner instance.
   * Commands and panels use this to execute grove CLI calls.
   */
  getRunner() {
    return this.runner;
  }
};
